Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -110,4 +110,71 @@ jobs:
         run: |
           set -e
           chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ matrix.tests }}' --no-color=false
-
+      - name: Install N4K v1.10
+        run: |
+          helm repo add nirmata https://nirmata.github.io/kyverno-charts/
+          helm install kyverno nirmata/kyverno \
+            --version=v3.0.29 \
+            --namespace kyverno \
+            --create-namespace 
+            # --set admissionController.replicas=1 \
+            # --set cleanupController.enabled=false \
+            # --set reportsController.enabled=false \
+            # --set backgroundController.enabled=false \
+            # --set crds.backgroundscanreports=false \
+            # --set crds.clusterbackgroundscanreports=false \
+            # --set crds.clusterpolicyreports=false \
+            # --set crds.policyreports=false \
+            # --set crds.cleanuppolicies=false
+          sleep 15
+          kypods=$(kubectl get pods -n kyverno -o jsonpath='{.items[*].metadata.name}')
+          for pd in ${kypods}; do
+            kubectl wait --for=condition=ready pod/$pd -n kyverno --timeout=300s
+          done
+          kubectl get pods -A
+      - name: Install CRDs
+        run: |
+          set -e
+          kubectl apply -f ./.chainsaw/crds
+      - name: Install Chainsaw
+        uses: kyverno/action-install-chainsaw@995cddaee7702e849270b84fa44cdcebe7462da8 # v0.1.9
+      - name: Test with Chainsaw
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -e
+          chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ matrix.tests }}' --no-color=false
+      - name: Install N4K v1.11
+        run: |
+          helm repo add nirmata https://nirmata.github.io/kyverno-charts/
+          helm install kyverno nirmata/kyverno \
+            --version=v3.1.17 \
+            --namespace kyverno \
+            --create-namespace 
+            # --set admissionController.replicas=1 \
+            # --set cleanupController.enabled=false \
+            # --set reportsController.enabled=false \
+            # --set backgroundController.enabled=false \
+            # --set crds.backgroundscanreports=false \
+            # --set crds.clusterbackgroundscanreports=false \
+            # --set crds.clusterpolicyreports=false \
+            # --set crds.policyreports=false \
+            # --set crds.cleanuppolicies=false
+          sleep 15
+          kypods=$(kubectl get pods -n kyverno -o jsonpath='{.items[*].metadata.name}')
+          for pd in ${kypods}; do
+            kubectl wait --for=condition=ready pod/$pd -n kyverno --timeout=300s
+          done
+          kubectl get pods -A
+      - name: Install CRDs
+        run: |
+          set -e
+          kubectl apply -f ./.chainsaw/crds
+      - name: Install Chainsaw
+        uses: kyverno/action-install-chainsaw@995cddaee7702e849270b84fa44cdcebe7462da8 # v0.1.9
+      - name: Test with Chainsaw
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -e
+          chainsaw test --config .chainsaw.yaml --include-test-regex '^chainsaw$/${{ matrix.tests }}' --no-color=false
